#!/usr/bin/env python3
import json
import os

def generate_tutorial_notebooks():
    # Common metadata
    metadata = {
        "kernelspec": {
            "display_name": "Python 3 (ipykernel)",
            "language": "python",
            "name": "python3"
        },
        "language_info": {
            "codemirror_mode": {
                "name": "ipython",
                "version": 3
            },
            "file_extension": ".py",
            "mimetype": "text/x-python",
            "name": "python",
            "nbconvert_exporter": "python",
            "pygments_lexer": "ipython3",
            "version": "3.10.12"
        }
    }

    # =========================================================================
    # 1. STUDENT NOTEBOOK
    # =========================================================================
    student_cells = []

    # Title & Overview
    student_cells.append({
        "cell_type": "markdown",
        "metadata": {},
        "source": [
            "# Supplementary Classroom Tutorial: Parsing Raw AMPT Output & Particle Rapidity Analysis\n",
            "=========================================================================================\n",
            "\n",
            "In this classroom laboratory, we will learn **step-by-step** how to write a raw text file parser in Python to read the output files generated by the **A Multi-Phase Transport (AMPT)** model. We will write our own parser from scratch to inspect the data structure, extract particle momenta, and calculate and compare rapidity ($y$) distributions for different particle species.\n",
            "\n",
            "### Pedagogical Split:\n",
            "- **Instructor Demonstration:** Step-by-step walkthrough using the **7.7 GeV** dataset (`../Data/subsets/ampt_7.7_sub100.dat`).\n",
            "- **Student Hands-on Task:** Replicate the parser and perform the analysis using the **39 GeV** dataset (`../Data/subsets/ampt_39_sub100.dat`), and make comparative physical observations.\n",
            "\n",
            "---\n",
            "\n",
            "## The AMPT Output Format (`ampt.dat`)\n",
            "An AMPT data file is a text file containing consecutive events. Each event starts with an **Event Header** line, followed by $N$ **Particle Data** lines (where $N$ is the number of particles in that event).\n",
            "\n",
            "### 1. Event Header Line Structure (Key Columns):\n",
            "- Column 1: `Event Number`\n",
            "- Column 3: `Number of Particles` (we use this to know how many subsequent lines to read as particles!)\n",
            "- Column 4: `Impact Parameter` ($b$ in fm)\n",
            "- Columns 5-6: `Number of Participants` ($N_{\\mathrm{part1}}, N_{\\mathrm{part2}}$)\n",
            "\n",
            "### 2. Particle Data Line Structure (**9 columns** total, key columns listed below):\n",
            "| Col | Field | Description |\n",
            "|-----|-------|-------------|\n",
            "| 1   | `PID`  | PDG particle ID: $\\pi^+ = 211$, $\\pi^- = -211$, $K^+ = 321$, $p = 2212$, $\\pi^0 = 111$, $\\gamma = 22$ … |\n",
            "| 2   | `px`   | x-momentum (GeV/$c$) |\n",
            "| 3   | `py`   | y-momentum (GeV/$c$) |\n",
            "| 4   | `pz`   | z-momentum (GeV/$c$, along beam) |\n",
            "| 5   | `mass` | Rest mass (GeV/$c^2$) |\n",
            "| 6–9 | `x y z t` | Production spacetime (fm, fm/$c$) — not used for momentum analysis |\n",
            "\n",
            "> **Key distinction:** Event header lines have **11 columns**; particle lines have **9 columns**.\n",
            "> The parser uses `num_particles` from the header so it *never* needs to guess which type a line is."
        ]
    })

    # Part 1: Instructor Demo Header
    student_cells.append({
        "cell_type": "markdown",
        "metadata": {},
        "source": [
            "## Part 1: Instructor Demonstration — Parsing the 7.7 GeV Dataset\n",
            "\n",
            "We will now write a simple, clean file parser in Python using standard file operations (`open()`, `.readline()`, and `.split()`) to read `../Data/subsets/ampt_7.7_sub100.dat`."
        ]
    })

    # Student Section: Code Cell for Parser skeleton
    student_cells.append({
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": [
            "import numpy as np\n",
            "import matplotlib.pyplot as plt\n",
            "\n",
            "# Let's define a charge lookup mapping for common particles\n",
            "CHARGE_MAP = {\n",
            "    211: 1,     # pi+\n",
            "    -211: -1,   # pi-\n",
            "    111: 0,     # pi0\n",
            "    321: 1,     # K+\n",
            "    -321: -1,   # K-\n",
            "    311: 0,     # K0\n",
            "    -311: 0,    # anti-K0\n",
            "    310: 0,     # K_Short\n",
            "    130: 0,     # K_Long\n",
            "    2212: 1,    # proton\n",
            "    -2212: -1,  # antiproton\n",
            "    2112: 0,    # neutron\n",
            "    -2112: 0,   # antineutron\n",
            "    11: -1,     # electron\n",
            "    -11: 1,     # positron\n",
            "    22: 0       # photon\n",
            "}\n",
            "\n",
            "def parse_ampt_file(filepath, max_events=100):\n",
            "    '''\n",
            "    Parse an AMPT ampt.dat file into a list of event dicts.\n",
            "\n",
            "    File layout\n",
            "    -----------\n",
            "    Every event starts with exactly ONE Event Header line (11 columns):\n",
            "        col 0: event_id\n",
            "        col 1: test_run\n",
            "        col 2: nparticles   <-- tells us how many particle lines follow\n",
            "        col 3: b (impact parameter, fm)\n",
            "        col 4-5: Npart_proj, Npart_targ\n",
            "        col 6-9: elastic/inelastic collision counts\n",
            "        col 10: phi_RP (reaction-plane angle)\n",
            "\n",
            "    Followed by nparticles Particle Data lines (9 columns each):\n",
            "        col 0: PID (PDG code)\n",
            "        col 1: px  (GeV/c)\n",
            "        col 2: py  (GeV/c)\n",
            "        col 3: pz  (GeV/c, along beam axis)\n",
            "        col 4: mass (GeV/c^2)\n",
            "        col 5-8: x, y, z, t  (production spacetime, fm / fm/c)\n",
            "\n",
            "    KEY: We use nparticles from the header so we NEVER need to guess\n",
            "    whether a line is a header or particle — headers (11 cols) and\n",
            "    particles (9 cols) are always read in the correct sequence.\n",
            "    '''\n",
            "    events = []\n",
            "    with open(filepath, 'r') as f:\n",
            "        for ev_idx in range(max_events):\n",
            "            # --- Step 1: read the event header line (11 columns) ---\n",
            "            header_line = f.readline()\n",
            "            if not header_line:\n",
            "                break  # end of file\n",
            "\n",
            "            parts = header_line.split()\n",
            "\n",
            "            # Guard: event header must have exactly 11 columns.\n",
            "            # If we see fewer, the file is done or corrupted — stop.\n",
            "            if len(parts) != 11:\n",
            "                break\n",
            "\n",
            "            event_num     = int(parts[0])\n",
            "            num_particles = int(parts[2])   # 3rd column = particle count\n",
            "            impact_param  = float(parts[3]) # 4th column = impact parameter (fm)\n",
            "\n",
            "            # --- Step 2: read exactly num_particles particle lines (9 columns each) ---\n",
            "            particles = []\n",
            "            for _ in range(num_particles):\n",
            "                p_line = f.readline()\n",
            "                if not p_line:\n",
            "                    break  # unexpected EOF\n",
            "                p_parts = p_line.split()\n",
            "\n",
            "                # Guard: particle lines must have exactly 9 columns.\n",
            "                # An 11-column line here would mean the event structure\n",
            "                # is misaligned — skip it and warn.\n",
            "                if len(p_parts) != 9:\n",
            "                    print(f'WARNING (event {event_num}): expected 9-column particle line,\\n'\n",
            "                          f'  got {len(p_parts)} columns: {p_line.strip()}')\n",
            "                    continue\n",
            "\n",
            "                pid  = int(p_parts[0])\n",
            "                px   = float(p_parts[1])\n",
            "                py   = float(p_parts[2])\n",
            "                pz   = float(p_parts[3])\n",
            "                mass = float(p_parts[4])\n",
            "                # p_parts[5:9] are x, y, z, t (spacetime) — not used here\n",
            "\n",
            "                particles.append({\n",
            "                    'pid':  pid,\n",
            "                    'px':   px,\n",
            "                    'py':   py,\n",
            "                    'pz':   pz,\n",
            "                    'mass': mass,\n",
            "                })\n",
            "\n",
            "            events.append({\n",
            "                'event_num':    event_num,\n",
            "                'impact_param': impact_param,\n",
            "                'particles':    particles,\n",
            "            })\n",
            "    return events\n",
            "\n",
            "# Load the 7.7 GeV dataset\n",
            "file_7_7 = '../Data/subsets/ampt_7.7_sub100.dat'\n",
            "events_7_7 = parse_ampt_file(file_7_7, max_events=100)\n",
            "print(f'Successfully parsed {len(events_7_7)} events from 7.7 GeV dataset.')\n",
            "print(f\"Event 1: {len(events_7_7[0]['particles'])} particles, \"",
            "      f\"b = {events_7_7[0]['impact_param']:.2f} fm\")"
        ]
    })

    # Calculations & Plotting Demo
    student_cells.append({
        "cell_type": "markdown",
        "metadata": {},
        "source": [
            "### Calculating Kinematics and Species Classification\n",
            "Let's write functions to compute transverse momentum $p_T$ and rapidity $y$:\n",
            "$$p_T = \\sqrt{p_x^2 + p_y^2}$$\n",
            "$$y = \\frac{1}{2} \\ln\\left( \\frac{E + p_z}{E - p_z} \\right), \\quad \\text{where } E = \\sqrt{p_T^2 + p_z^2 + m^2}$$"
        ]
    })

    student_cells.append({
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "source": [
            "def calculate_pt(px, py):\n",
            "    return np.sqrt(px**2 + py**2)\n",
            "\n",
            "def calculate_rapidity(px, py, pz, mass):\n",
            "    pt = calculate_pt(px, py)\n",
            "    E = np.sqrt(pt**2 + pz**2 + mass**2)\n",
            "    # Protect against divide-by-zero or negative arguments inside log\n",
            "    numerator = E + pz\n",
            "    denominator = np.maximum(E - pz, 1e-15)\n",
            "    return 0.5 * np.log(numerator / denominator)\n",
            "\n",
            "# Let's filter and analyze species at 7.7 GeV\n",
            "y_pions = []\n",
            "y_kaons = []\n",
            "y_protons = []\n",
            "y_charged = []\n",
            "y_neutral = []\n",
            "\n",
            "for ev in events_7_7:\n",
            "    for p in ev['particles']:\n",
            "        y = calculate_rapidity(p['px'], p['py'], p['pz'], p['mass'])\n",
            "        pid_abs = np.abs(p['pid'])\n",
            "        \n",
            "        # Species classification\n",
            "        if pid_abs == 211: # Charged Pions\n",
            "            y_pions.append(y)\n",
            "        elif pid_abs == 321: # Charged Kaons\n",
            "            y_kaons.append(y)\n",
            "        elif pid_abs == 2212: # Protons\n",
            "            y_protons.append(y)\n",
            "            \n",
            "        # Charged vs. Neutral classification\n",
            "        charge = CHARGE_MAP.get(p['pid'], None)\n",
            "        if charge is not None:\n",
            "            if charge != 0:\n",
            "                y_charged.append(y)\n",
            "            else:\n",
            "                y_neutral.append(y)\n",
            "\n",
            "# Create demonstration plot\n",
            "fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(14, 5.5))\n",
            "\n",
            "# Plot 1: Identified Charged Particles\n",
            "bins = np.linspace(-3.0, 3.0, 30)\n",
            "ax1.hist(y_pions, bins=bins, histtype='step', color='blue', linewidth=1.8, label=r'Pions ($\\pi^\\pm$)')\n",
            "ax1.hist(y_kaons, bins=bins, histtype='step', color='green', linewidth=1.8, label=r'Kaons ($K^\\pm$)')\n",
            "ax1.hist(y_protons, bins=bins, histtype='step', color='red', linewidth=1.8, label=r'Protons ($p/\\bar{p}$)')\n",
            "ax1.set_xlabel('Rapidity y', fontsize=12)\n",
            "ax1.set_ylabel('dI/dy', fontsize=12)\n",
            "ax1.set_title('Identified Charged Particle Rapidity (7.7 GeV)', fontsize=13)\n",
            "ax1.grid(True, linestyle=':', alpha=0.6)\n",
            "ax1.legend(frameon=True)\n",
            "\n",
            "# Plot 2: Charged vs. Neutral\n",
            "ax2.hist(y_charged, bins=bins, histtype='stepfilled', color='#6366f1', alpha=0.4, edgecolor='#4f46e5', linewidth=1.8, label='All Charged Particles')\n",
            "ax2.hist(y_neutral, bins=bins, histtype='step', color='orange', linewidth=1.8, label='All Neutral Particles')\n",
            "ax2.set_xlabel('Rapidity y', fontsize=12)\n",
            "ax2.set_ylabel('dI/dy', fontsize=12)\n",
            "ax2.set_title('Charged vs. Neutral Multiplicities (7.7 GeV)', fontsize=13)\n",
            "ax2.grid(True, linestyle=':', alpha=0.6)\n",
            "ax2.legend(frameon=True)\n",
            "\n",
            "plt.show()"
        ]
    })

    # Part 2: Student Hands-on task
    student_cells.append({
        "cell_type": "markdown",
        "metadata": {},
        "source": [
            "## Part 2: Student Hands-on Lab — Parsing the 39 GeV Dataset\n",
            "\n",
            "Now it is your turn! You will adapt the parser and run the analysis on the higher energy **39 GeV** dataset. This will allow you to see how particle yields and longitudinal shapes change due to the collision energy.\n",
            "\n",
            "### Your Tasks:\n",
            "1. Parse the 39 GeV dataset `../Data/subsets/ampt_39_sub100.dat` for 100 events.\n",
            "2. Extract $y$ distributions for charged pions, charged kaons, and protons.\n",
            "3. Extract $y$ distributions for all charged particles vs. neutral particles.\n",
            "4. Plot the results in a 2-panel chart (just like the demonstration above).\n",
            "5. **Physical Discussion Questions:**\n",
            "   - Compare the peak value of $dN/dy$ for pions between 7.7 GeV and 39 GeV. What does this tell you about particle production scaling?\n",
            "   - Look at the width of the rapidity distributions. How does the width of the distribution scale with beam energy, and how does this relate to the kinematic beam rapidity limit $y_{\\mathrm{beam}}$?"
        ]
    })

    # Student work cell
    student_cells.append({
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": [
            "# TODO: Define path to the 39 GeV file\n",
            "file_39 = \"../Data/subsets/ampt_39_sub100.dat\"\n",
            "\n",
            "# TODO: Parse the 39 GeV dataset for 100 events\n",
            "\n",
            "\n",
            "# TODO: Initialize list arrays for pions, kaons, protons, charged, and neutral particles\n",
            "\n",
            "\n",
            "# TODO: Iterate over events, compute rapidity, and classify particles\n",
            "\n",
            "\n",
            "# TODO: Plot the identified particles and charged vs. neutral distributions for 39 GeV\n",
            "# Hint: Use the 7.7 GeV plotting code as a reference template!\n"
        ]
    })

    # Discussion Markdown cell
    student_cells.append({
        "cell_type": "markdown",
        "metadata": {},
        "source": [
            "### Student Physical Discussion Responses\n",
            "*(Write your brief explanations and comparisons here)*"
        ]
    })

    # Save student notebook
    script_dir = os.path.dirname(os.path.abspath(__file__))
    student_path = os.path.join(script_dir, "..", "exercises", "ampt_parsing_tutorial.ipynb")
    student_nb = {"cells": student_cells, "metadata": metadata, "nbformat": 4, "nbformat_minor": 2}
    with open(student_path, "w") as f:
        json.dump(student_nb, f, indent=1)
    print(f"Created {student_path}")


    # =========================================================================
    # 2. SOLUTIONS NOTEBOOK
    # =========================================================================
    solution_cells = []

    # Title & Overview
    solution_cells.append({
        "cell_type": "markdown",
        "metadata": {},
        "source": [
            "# Supplementary Classroom Tutorial: Parsing Raw AMPT Output & Particle Rapidity Analysis (Solutions)\n",
            "===================================================================================================\n",
            "\n",
            "This notebook contains the reference code and completed analysis solutions for the supplementary AMPT parsing and kinematics tutorial."
        ]
    })

    # Copy cells up to student tasks
    for i in range(1, 5):
        solution_cells.append(student_cells[i])

    # Add Solutions work cell
    solution_cells.append({
        "cell_type": "markdown",
        "metadata": {},
        "source": [
            "## Solutions: Part 2 — Parsing and Analysis of the 39 GeV Dataset"
        ]
    })

    solution_cells.append({
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": [
            "file_39 = \"../Data/subsets/ampt_39_sub100.dat\"\n",
            "events_39 = parse_ampt_file(file_39, max_events=100)\n",
            "print(f\"Successfully parsed {len(events_39)} events from 39 GeV dataset.\")\n",
            "\n",
            "y_pions_39 = []\n",
            "y_kaons_39 = []\n",
            "y_protons_39 = []\n",
            "y_charged_39 = []\n",
            "y_neutral_39 = []\n",
            "\n",
            "for ev in events_39:\n",
            "    for p in ev['particles']:\n",
            "        y = calculate_rapidity(p['px'], p['py'], p['pz'], p['mass'])\n",
            "        pid_abs = np.abs(p['pid'])\n",
            "        \n",
            "        # Species classification\n",
            "        if pid_abs == 211: # Charged Pions\n",
            "            y_pions_39.append(y)\n",
            "        elif pid_abs == 321: # Charged Kaons\n",
            "            y_kaons_39.append(y)\n",
            "        elif pid_abs == 2212: # Protons\n",
            "            y_protons_39.append(y)\n",
            "            \n",
            "        # Charged vs. Neutral classification\n",
            "        charge = CHARGE_MAP.get(p['pid'], None)\n",
            "        if charge is not None:\n",
            "            if charge != 0:\n",
            "                y_charged_39.append(y)\n",
            "            else:\n",
            "                y_neutral_39.append(y)\n",
            "\n",
            "# Create comparison plots for 39 GeV\n",
            "fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(14, 5.5))\n",
            "\n",
            "# Plot 1: Identified Charged Particles\n",
            "bins = np.linspace(-4.5, 4.5, 30)\n",
            "ax1.hist(y_pions_39, bins=bins, histtype='step', color='blue', linewidth=1.8, label=r'Pions ($\\pi^\\pm$)')\n",
            "ax1.hist(y_kaons_39, bins=bins, histtype='step', color='green', linewidth=1.8, label=r'Kaons ($K^\\pm$)')\n",
            "ax1.hist(y_protons_39, bins=bins, histtype='step', color='red', linewidth=1.8, label=r'Protons ($p/\\bar{p}$)')\n",
            "ax1.set_xlabel('Rapidity y', fontsize=12)\n",
            "ax1.set_ylabel('dI/dy', fontsize=12)\n",
            "ax1.set_title('Identified Charged Particle Rapidity (39 GeV)', fontsize=13)\n",
            "ax1.grid(True, linestyle=':', alpha=0.6)\n",
            "ax1.legend(frameon=True)\n",
            "\n",
            "# Plot 2: Charged vs. Neutral\n",
            "ax2.hist(y_charged_39, bins=bins, histtype='stepfilled', color='#6366f1', alpha=0.4, edgecolor='#4f46e5', linewidth=1.8, label='All Charged Particles')\n",
            "ax2.hist(y_neutral_39, bins=bins, histtype='step', color='orange', linewidth=1.8, label='All Neutral Particles')\n",
            "ax2.set_xlabel('Rapidity y', fontsize=12)\n",
            "ax2.set_ylabel('dI/dy', fontsize=12)\n",
            "ax2.set_title('Charged vs. Neutral Multiplicities (39 GeV)', fontsize=13)\n",
            "ax2.grid(True, linestyle=':', alpha=0.6)\n",
            "ax2.legend(frameon=True)\n",
            "\n",
            "plt.show()"
        ]
    })

    # Add Solutions physical discussion
    solution_cells.append({
        "cell_type": "markdown",
        "metadata": {},
        "source": [
            "### Solution: Physical Discussion & Observations\n",
            "\n",
            "1. **Peak Multiplicity Scaling ($dN/dy$):**\n",
            "   - At **7.7 GeV**, the peak of the pion rapidity distribution yields $\\approx 3,000$ pions overall in our hist count (scaled by event, it is much smaller, $\\approx 30$ per event per unit rapidity).\n",
            "   - At **39 GeV**, the peak pion yield is significantly higher (over $\\approx 12,000$ total count, $\\approx 120$ per event per unit rapidity). This is a direct physical consequence of the increased collision energy, allowing for much greater excitation of the color fields and particle production from ZPC parton cascades.\n",
            "\n",
            "2. **Rapidity Distribution Width ($y_{\\mathrm{beam}}$ limits):**\n",
            "   - The width of the distributions grows significantly as the beam energy increases from 7.7 GeV to 39 GeV.\n",
            "   - At 7.7 GeV, the particles are constrained within a narrow rapidity space since the kinematic limit is $y_{\\mathrm{beam}} \\approx 1.41$.\n",
            "   - At 39 GeV, the phase space expands longitudinally, with $y_{\\mathrm{beam}} \\approx 3.03$. The distributions become broad plateaus, demonstrating that higher energy collisions open up wider rapidity gaps, which allows particle production to spread over a much larger longitudinal range."
        ]
    })

    # Save solutions notebook
    solution_path = os.path.join(script_dir, "..", "exercises", "ampt_parsing_tutorial_solutions.ipynb")
    solution_nb = {"cells": solution_cells, "metadata": metadata, "nbformat": 4, "nbformat_minor": 2}
    with open(solution_path, "w") as f:
        json.dump(solution_nb, f, indent=1)
    print(f"Created {solution_path}")

if __name__ == "__main__":
    generate_tutorial_notebooks()
